### PR TITLE
mockup ideas for the client

### PR DESCRIPTION
**Pull request by nephiw**
- Added a few grunt tasks to make this easier and the conversion
  from "mockup" to product easier.
- Started work to make the application take up 100% of the height.
- Nothing is pretty yet, but it is started.

### CODE REVIEW

**Comment by nephiw** [comment]
I am not sure that I like how I did this. I may look into user bower and excluding the bower dependencies from git instead of duplicating bootstrap in our repo.

**Comment by MakotoTheKnight** [comment]
Just taking a preliminary (late night) glance at GitHub...did notice that there was a decent amount of boilerplate in this.  If it makes it easier to get the front end bootstrapped I'm fine with it, but if it's possible, how much could we cut down on?

**Comment by nephiw** [comment]
@MakotoTheKnight no boilerplate actually - all hand coded. But a lot of bootstrap source gets added on the initial commit. We can talk about what we actually use, but I am experimenting right now. Quickly adding things means not removing unused things.

Note that I am just using bootstrap and it's dependency of jQuery to get set up. If we chose a design, then I will switch to, likely, angular and bootstrap as well as using bower to do dependency instead of including all of those files in the repo.

I figured something was better than nothing at this point. I didn't want to move straight to perfect as then I would never do anything. :smile:

**Comment by nephiw** [comment]
We should definitely discuss why I set it up this way in person.

**Comment by djmittens** [comment]
FYI, bootstrap code is in fact boilerplate :smile: , unless you mean bootstrap as in library in which case you totally can avoid checking that in all together.
And grunt is so old school nowadays, its all about the gulp, no trebble.

**Comment by nephiw** [comment]
@djmittens all of this code is disposable. It will not make it into the product. I am just using it to create mockups to use during dicussions at AoC. 

I have a lot of experience working within existing projects, but little experience building projects from scratch, so that is why I am even using grunt at all. I am practicing setting things up and likely bumbling. As for gulp being better than grunt... that is disputable and my position is to use what works. Maybe next time I will simply use npm for my build system.

**Comment by nephiw** [comment]
@MakotoTheKnight and @djmittens there - now it uses bower so I deleted the lib folder that contained the less files.

**Pull request closed without merging**
